version: "3.3"

services:
    server:
        container_name: go-book-crud
        build: .
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        volumes:
            - .:/src/go-book-crud/
        env_file: .env.dev

    postgres:
        container_name: go-book-crud-postgres
        image: postgres:alpine
        environment:
            POSTGRES_DB: go-book-crud
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor
        ports:
            - "5432:5432"
